version: '3'
services:
  avamar-api:
    ports:
      - "5000:5000"
    image:
      willnx/vlab-avamar-api
    environment:
      - VLAB_URL=https://localhost
      - INF_VCENTER_SERVER=virtlab.igs.corp
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=1.Password
    volumes:
      - ./vlab_avamar_api:/usr/lib/python3.8/site-packages/vlab_avamar_api
    command: ["python3", "app.py"]

  avamar-worker:
    image:
      willnx/vlab-avamar-worker
    volumes:
      - ./vlab_avamar_api:/usr/lib/python3.8/site-packages/vlab_avamar_api
      - /mnt/raid/images/avamar:/images:ro
    environment:
      - INF_VCENTER_SERVER=virtlab.igs.corp
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=1.Password
      - INF_VCENTER_TOP_LVL_DIR=/vlab

  avamar-broker:
    image:
      rabbitmq:3.7-alpine
